CREATE DATABASE IF NOT EXISTS Public_Library;

USE Public_Library;
CREATE TABLE Members (
	M_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    M_Name VARCHAR (255) NOT NULL,
    Gender CHAR(1) DEFAULT NULL,
    DOB DATE,
    Address VARCHAR(255) DEFAULT NULL,
    Phone BIGINT DEFAULT NULL,
    E_MAIL VARCHAR (255) DEFAULT NULL,
    Card_Number VARCHAR(255),
    ID_Number VARCHAR(50)
);

CREATE TABLE Card_Details (
	Card_Number VARCHAR(255) NOT NULL PRIMARY KEY,
    Card_Type VARCHAR(10),
    Card_Bank VARCHAR (50),
    Card_Expiry YEAR
);

ALTER TABLE Members 
	ADD FOREIGN KEY (Card_Number) REFERENCES Card_Details(Card_Number) ON UPDATE CASCADE ON DELETE RESTRICT;

CREATE TABLE M_Identity(
	ID_Number VARCHAR(50) NOT NULL PRIMARY KEY,
    ID_Type VARCHAR (20)
);

ALTER TABLE Members 
	ADD FOREIGN KEY (ID_Number) REFERENCES M_Identity(ID_Number) ON UPDATE CASCADE ON DELETE RESTRICT;
    
CREATE TABLE M_ADDTL_INFO (
	ID_Number VARCHAR(50) NOT NULL PRIMARY KEY,
    Member_Type VARCHAR (20),
	Member_Status VARCHAR (20)
);

ALTER TABLE Members
	ADD FOREIGN KEY (ID_Number) REFERENCES M_ADDTL_INFO(ID_Number) ON UPDATE CASCADE ON DELETE RESTRICT;
    
